apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
data:

  smtp-username: eW91ci1lbWFpbEBnbWFpbC5jb20=
  smtp-password: a3JudCBhZ2RpIG12ZHcgY3Z6eA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
        - name: email-app
          image: omar99awaisha/email-services:v1.3
          ports:
            - containerPort: 8084
          env:
            # Kafka Configuration
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"

            # SMTP Configuration
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: smtp-password
---
apiVersion: v1
kind: Service
metadata:
  name: email-app
spec:
  type: NodePort
  selector:
    app: email-app
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084