apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-app
  labels:
    app: logger-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-app
  template:
    metadata:
      labels:
        app: logger-app
    spec:
      containers:
        - name: logger-app
          image: omar99awaisha/logger-services:v1.0
          ports:
            - containerPort: 8086
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/loggerDb"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: logger-app
  labels:
    app: logger-app
spec:
  type: NodePort
  selector:
    app: logger-app
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086
      protocol: TCP
      name: http