apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-app
  template:
    metadata:
      labels:
        app: metrics-app
    spec:
      containers:
        - name: metrics-app
          image: omar99awaisha/metric-services:v1.3
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: metricsdbcntr
            - name: DB_USER
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: DB_NAME
              value: MetricMsDb
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-app
spec:
  selector:
    app:  metrics-app
  ports:
    - port: 82
      targetPort: 8082