apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: security-app
  template:
    metadata:
      labels:
        app: security-app
    spec:
      containers:
        - name: security-app
          image: omar99awaisha/security-service:v1.4
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: securitydbcntr
            - name: DB_USER
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: security-mysql-secret
                  key: mysql-password
            - name: DB_NAME
              value: security_db
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: security-jwt-secret
                  key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: security-app
spec:
  type: NodePort
  selector:
    app: security-app
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30087