apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-app
  labels:
    app: sms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-app
  template:
    metadata:
      labels:
        app: sms-app
    spec:
      containers:
        - name: sms-app
          image: omar99awaisha/sms-services:v1.0
          ports:
            - containerPort: 8085
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: twilio-account-sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: twilio-auth-token
            - name: TWILIO_OUTGOING_SMS_NUMBER
              valueFrom:
                secretKeyRef:
                  name: sms-secret
                  key: twilio-phone-number
---
apiVersion: v1
kind: Service
metadata:
  name: sms-app
  labels:
    app: sms-app
spec:
  type: NodePort
  selector:
    app: sms-app
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085