apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: omar99awaisha/user-service:v1.1
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: userdbcntr
            - name: DB_USER
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-mysql-secret
                  key: mysql-password
            - name: DB_NAME
              value: mst_user_db
            - name: SERVER_PORT
              value: "8084"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-app
spec:
  type: NodePort
  selector:
    app: user-app
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30088